---
# vars file for run_docker_compose
gitlab_image: gitlab/gitlab-ce:17.8.0-ce.0
gitlab_container_name: gitlab
gitlab_hostname: gitlab.local
gitlab_web_protocol: http
gitlab_shell_ssh_port: 2424
gitlab_http_port: 80
gitlab_https_port: 8443
gitlab_ssh_port: 2424
gitlab_config_dir_host: ./data/docker/gitlab/etc/gitlab
gitlab_logs_dir_host: ./data/docker/gitlab/var/opt/gitlab
gitlab_data_dir_host: ./data/docker/gitlab/var/log/gitlab

laboratory_home: /opt/docker-compose