---
# tasks file for docker_install
- name: Install dependencies
  ansible.builtin.yum:
    name:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
    update_cache: yes
    state: present

- name: Add repo docker
  ansible.builtin.yum_repository:
    name: docker
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: yes
    enabled: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install docker-ce
  ansible.builtin.yum:
    name: docker-ce
    update_cache: yes
    state: present

- name: Enabled docker.service
  ansible.builtin.systemd_service:
    state: started
    name: docker
    enabled: yes

- name: Get version docker
  ansible.builtin.command: docker version
  register: result
  changed_when: false

- name: Print version docker
  ansible.builtin.debug:
    var: result
    verbosity: 2