---
# tasks file for run_docker_compose
- name: Create HomeDir
  ansible.builtin.file:
    path: "{{ laboratory_home }}"
    state: directory

- name: Create Data Dir for Grafana
  ansible.builtin.file:
    path: "{{ laboratory_home }}/{{ grafana_data_dir_host }}"
    state: directory
    owner: 472
    group: 472

- name: Create Config Dir for Grafana
  ansible.builtin.file:
    path: "{{ laboratory_home }}/{{ grafana_config_dir_host }}"
    state: directory
    owner: 472
    group: 472

- name: Create Log Dir for Grafana
  ansible.builtin.file:
    path: "{{ laboratory_home }}/{{ grafana_log_dir_host }}"
    state: directory
    owner: 472
    group: 472

- name: Create Config Dir for Nginx
  ansible.builtin.file:
    path: "{{ laboratory_home }}/{{ nginx_config_dir_host }}"
    state: directory

- name: Copy grafana.conf
  ansible.builtin.template:
    src: grafana.conf.j2
    dest: "{{ laboratory_home }}/{{ nginx_config_dir_host }}/grafana.conf"

- name: Copy gitlab.conf
  ansible.builtin.template:
    src: gitlab.conf.j2
    dest: "{{ laboratory_home }}/{{ nginx_config_dir_host }}/gitlab.conf"

- name: Copy laboratory-compose file
  ansible.builtin.template:
    src: laboratory-compose.yml.j2
    dest: "{{ laboratory_home }}/laboratory-compose.yml"

- name: Copy laboratory systemd file
  ansible.builtin.template:
    src: laboratory.service.j2
    dest: /etc/systemd/system/laboratory.service

- name: Start laboratory service
  ansible.builtin.systemd_service:
    name: laboratory
    state: restarted
    enabled: yes
    daemon-reload: yes